import type { MediaItem } from "@/types/media";
import type { StreamerProfile } from "@/types/streamer";

/**
 * Local fallback data so the UI is fully browsable without a configured
 * Supabase project. `lib/queries.ts` swaps this out for real rows once
 * NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY are set.
 */

export const MOCK_STREAMER: StreamerProfile = {
  name: "NovaGiv",
  handle: "@novagiv",
  avatarUrl: "https://static-cdn.jtvnw.net/jtv_user_pictures/a11aa1f7-c873-4023-b481-698b07ed8d94-profile_image-70x70.png",
  bannerUrl: "https://picsum.photos/seed/novagiv-banner/1600/400",
  isLive: true,
  liveTitle: "Maratón de anime + karaoke nocturno",
  bio: "Resubidos organizados de mis transmisiones: películas, series, anime, votaciones y karaokes.",
  socials: [
    { platform: "twitch", url: "https://twitch.tv/novagiv" },
    { platform: "youtube", url: "https://youtube.com/@novagiv" },
    { platform: "website", url: "https://novagiv.vercel.app/" },
    { platform: "discord", url: "https://discord.gg/novagiv" },
    { platform: "x", url: "https://x.com/novagiv" },
  ],
};

export const MOCK_MEDIA: MediaItem[] = [
  {
    id: "1",
    title: "Estación Carmesí",
    slug: "estacion-carmesi",
    type: "movie",
    posterUrl: "https://picsum.photos/seed/estacion-carmesi/400/600",
    genres: ["Ciencia ficción", "Suspenso"],
    year: 2023,
    description:
      "Una tripulación varada en una estación orbital debe decidir quién regresa a casa cuando el oxígeno empieza a escasear.",
    createdAt: "2026-07-20T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000001",
    duration: "1h 52m",
    rating: 8.1,
  },
  {
    id: "2",
    title: "El Último Vals",
    slug: "el-ultimo-vals",
    type: "movie",
    posterUrl: "https://picsum.photos/seed/el-ultimo-vals/400/600",
    genres: ["Drama", "Romance"],
    year: 2019,
    description: "Dos bailarines reconstruyen su compañía tras el cierre del teatro que los vio nacer.",
    createdAt: "2026-06-02T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000002",
    duration: "2h 05m",
    rating: 7.4,
  },
  {
    id: "3",
    title: "Guardianes del Abismo",
    slug: "guardianes-del-abismo",
    type: "series",
    posterUrl: "https://picsum.photos/seed/guardianes-del-abismo/400/600",
    genres: ["Fantasía", "Aventura"],
    year: 2022,
    description:
      "Un grupo de exploradores custodia la frontera entre el mundo conocido y las criaturas que habitan bajo tierra.",
    createdAt: "2026-07-15T20:00:00.000Z",
    status: "ongoing",
    rating: 8.6,
    episodes: [
      { id: "3-s1e1", episodeNumber: 1, seasonNumber: 1, title: "El descenso", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000010", duration: "42m" },
      { id: "3-s1e2", episodeNumber: 2, seasonNumber: 1, title: "Ecos de piedra", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000011", duration: "45m" },
      { id: "3-s1e3", episodeNumber: 3, seasonNumber: 1, title: "El pacto", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000012", duration: "40m" },
      { id: "3-s2e1", episodeNumber: 1, seasonNumber: 2, title: "Nuevas grietas", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000013", duration: "44m" },
      { id: "3-s2e2", episodeNumber: 2, seasonNumber: 2, title: "El precio de la luz", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000014", duration: "47m" },
    ],
  },
  {
    id: "4",
    title: "Código Ámbar",
    slug: "codigo-ambar",
    type: "series",
    posterUrl: "https://picsum.photos/seed/codigo-ambar/400/600",
    genres: ["Suspenso", "Drama"],
    year: 2021,
    description: "Una analista de inteligencia descubre un patrón que nadie más quiere ver.",
    createdAt: "2026-05-18T20:00:00.000Z",
    status: "completed",
    rating: 7.9,
    episodes: [
      { id: "4-e1", episodeNumber: 1, title: "Ruido de fondo", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000020", duration: "50m" },
      { id: "4-e2", episodeNumber: 2, title: "Falsos positivos", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000021", duration: "48m" },
      { id: "4-e3", episodeNumber: 3, title: "Punto ciego", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000022", duration: "51m" },
      { id: "4-e4", episodeNumber: 4, title: "Cierre", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000023", duration: "55m" },
    ],
  },
  {
    id: "5",
    title: "Luz de Luna Escarlata",
    slug: "luz-de-luna-escarlata",
    type: "anime",
    posterUrl: "https://picsum.photos/seed/luz-de-luna-escarlata/400/600",
    genres: ["Fantasía", "Acción", "Romance"],
    year: 2024,
    description: "Una cazadora de espíritus y un noble caído se enfrentan a un culto que quiere despertar a la luna roja.",
    createdAt: "2026-07-24T20:00:00.000Z",
    status: "ongoing",
    rating: 8.9,
    episodes: [
      { id: "5-e1", episodeNumber: 1, title: "La cazadora", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000030", duration: "24m" },
      { id: "5-e2", episodeNumber: 2, title: "El noble caído", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000031", duration: "24m" },
      { id: "5-e3", episodeNumber: 3, title: "Culto de sangre", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000032", duration: "23m" },
      { id: "5-e4", episodeNumber: 4, title: "Luna llena", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000033", duration: "25m" },
      { id: "5-e5", episodeNumber: 5, title: "El precio del pacto", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000034", duration: "24m" },
    ],
  },
  {
    id: "6",
    title: "Academia Kitsune",
    slug: "academia-kitsune",
    type: "anime",
    posterUrl: "https://picsum.photos/seed/academia-kitsune/400/600",
    genres: ["Comedia", "Slice of Life"],
    year: 2020,
    description: "Un estudiante torpe descubre que su nueva escuela entrena a espíritus zorro para convivir con humanos.",
    createdAt: "2026-04-11T20:00:00.000Z",
    status: "completed",
    rating: 7.6,
    episodes: [
      { id: "6-e1", episodeNumber: 1, title: "Bienvenido, humano", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000040", duration: "22m" },
      { id: "6-e2", episodeNumber: 2, title: "Colmillos y modales", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000041", duration: "22m" },
      { id: "6-e3", episodeNumber: 3, title: "El festival de otoño", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000042", duration: "23m" },
    ],
  },
  {
    id: "7",
    title: "Votación: Mejor Villano de la Temporada",
    slug: "votacion-mejor-villano-temporada",
    type: "special",
    posterUrl: "https://picsum.photos/seed/votacion-villano/400/600",
    genres: ["Especial"],
    year: 2026,
    description: "Día de votación en vivo: la comunidad elige al antagonista favorito entre las series vistas este mes.",
    createdAt: "2026-07-27T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000050",
    duration: "1h 10m",
  },
  {
    id: "8",
    title: "Día de Votación: Próxima Película",
    slug: "dia-de-votacion-proxima-pelicula",
    type: "special",
    posterUrl: "https://picsum.photos/seed/votacion-pelicula/400/600",
    genres: ["Especial"],
    year: 2026,
    description: "El chat decide qué película se transmite la próxima semana entre cuatro finalistas.",
    createdAt: "2026-06-29T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000051",
    duration: "48m",
  },
  {
    id: "9",
    title: "Karaoke Nocturno: Éxitos 2000s",
    slug: "karaoke-nocturno-exitos-2000s",
    type: "karaoke",
    posterUrl: "https://picsum.photos/seed/karaoke-2000s/400/600",
    genres: ["Musical"],
    year: 2026,
    description: "Sesión completa de karaoke con lo mejor de los 2000s, pedidos del chat incluidos.",
    createdAt: "2026-07-26T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000060",
    duration: "2h 20m",
  },
  {
    id: "10",
    title: "Karaoke Especial: Openings de Anime",
    slug: "karaoke-especial-openings-anime",
    type: "karaoke",
    posterUrl: "https://picsum.photos/seed/karaoke-openings/400/600",
    genres: ["Musical"],
    year: 2025,
    description: "Un repaso cantado por los openings y endings más pedidos por la comunidad.",
    createdAt: "2026-03-08T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000061",
    duration: "1h 45m",
  },
  {
    id: "11",
    title: "El Peso del Silencio",
    slug: "el-peso-del-silencio",
    type: "movie",
    posterUrl: "https://picsum.photos/seed/el-peso-del-silencio/400/600",
    genres: ["Drama", "Terror"],
    year: 2018,
    description: "Una familia se muda a una casa donde el ruido, literalmente, atrae al peligro.",
    createdAt: "2026-02-14T20:00:00.000Z",
    okRuEmbedUrl: "https://ok.ru/videoembed/0000000000003",
    duration: "1h 38m",
    rating: 7.0,
  },
  {
    id: "12",
    title: "Piratas del Meridiano",
    slug: "piratas-del-meridiano",
    type: "anime",
    posterUrl: "https://picsum.photos/seed/piratas-del-meridiano/400/600",
    genres: ["Aventura", "Acción", "Comedia"],
    year: 2025,
    description: "Una tripulación improbable busca el mapa perdido que conecta todos los mares del mundo conocido.",
    createdAt: "2026-07-10T20:00:00.000Z",
    status: "ongoing",
    rating: 8.3,
    episodes: [
      { id: "12-e1", episodeNumber: 1, title: "Zarpando", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000070", duration: "24m" },
      { id: "12-e2", episodeNumber: 2, title: "El mapa roto", okRuEmbedUrl: "https://ok.ru/videoembed/0000000000071", duration: "24m" },
    ],
  },
];
